- name: Deploy trino-hive-docker
  hosts: host
  remote_user: "{{ lookup('env', 'REMOTE_USER') }}"
  tasks:
  - name: remove trino-hive-docker folder
    ansible.builtin.file:
      path: trino-hive-docker
      state: absent

  - name: Pull git repo
    ansible.builtin.git:
      repo: git@github.com:FAenX/trino-hive-docker.git
      dest: trino-hive-docker

  - name: run docker-compose up
    shell: |
      set -e
      cd trino-hive-docker/docker-compose
      docker-compose up -d --build